name: 'Pull Request Actions'

on:
  pull_request:
    # Only initiate the workflow when a PR is opened, or committed to.
    branches:
      - main

jobs:
  testAndLint:
    name: 'Test and Lint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v3

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Build has to go before lint and check because it creates the .svelte-kit directory
      - name: Build the site
        run: pnpm build:vite

      - name: Run Linting
        run: pnpm lint

      - name: Run Svelte check
        run: pnpm check
